version: '3.8'

services:
  backend: 
    build:
      context: ./backend
    container_name: connect-4-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    
  frontend:
    build:
      context: ./frontend
    container_name: connect-4-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend